### ISSUE TITLE
py3 branch

### ISSUE THREAD

**Issue by and3rson** [urwid/urwid#265]
@wardi Seems like most of the Python 3 support is in the `py3` branch. Does it mean that `master` is outdated?

Seems like `py3` branch is following a different structure. Also native Arch Linux package (version 1.3.1) seems to be built from this branch.

I think it would be better to keep the same codebase for both 2.x and 3.x.

**Comment by wardi** [comment]
the py3 branch is a remnant of python 3 compatibility work and is already merged. The code base supports python 2 and 3 using the 2to3 conversion script. I used 2to3 because at the time it was unreasonably difficult to support both versions from the same unmodified code base.

It would be great to move to unmodified python 2 and 3 code instead of using 2to3, but the py3 branch isn't what you're looking for

**Comment by and3rson** [comment]
Thanks. I think I'll integrate `six` and walk through all souces with 2to3 to manually make the code both 2- and 3-compatible. (Gonna be a hell of a mess with the byte/str types, sigh)

**Comment by and3rson** [comment]
Just saw the `compat.py` - probably gonna populate & use it instead of `six`.
