### ISSUE TITLE
Can anybody give me an example buiding an network address editing form?

### ISSUE THREAD

**Issue by yanzixiang** [urwid/urwid#299]
I use this code :
```python
def EditNetworkAddress(caption,callback):
  listbox_content = [
    blank,
    urwid.Columns([
      urwid.Text("ip"),
      urwid.AttrWrap(urwid.IntEdit("ip0", 192),'editbx', 'editfc' ),
      urwid.AttrWrap(urwid.IntEdit("ip1", 168),'editbx', 'editfc' ),
      urwid.AttrWrap(urwid.IntEdit("ip2", 123),'editbx', 'editfc' ),
      urwid.AttrWrap(urwid.IntEdit("ip3", 21),'editbx', 'editfc' ),
    ], 2),
    blank,
    urwid.Columns([
      urwid.AttrWrap(urwid.IntEdit("ip0", 192),'editbx', 'editfc' ),
      urwid.AttrWrap(urwid.IntEdit("ip1", 168),'editbx', 'editfc' ),
      urwid.AttrWrap(urwid.IntEdit("ip2", 123),'editbx', 'editfc' ),
      urwid.AttrWrap(urwid.IntEdit("ip3", 21),'editbx', 'editfc' ),
    ], 2)
  ]
  return urwid.ListBox(urwid.SimpleListWalker(listbox_content))
```
and get this 

AttributeError: 'ListBox' object has no attribute 'rows'

Can anybody give me some kind of help ?

**Comment by rndusr** [comment]
http://urwid.org/manual/widgets.html#box-flow-and-fixed-widgets

I've read this hundreds of times and still have to go back to it every time I get this error.

You probably have to wrap the listbox in another widget.

**Comment by ulidtko** [comment]
By the way, I'd advise **against** using 4 separate edits for 1 IP address.

Better: 1 edit, allowing to type (or paste from buffer!) a full dotted-decimal address, plus a function `validate_ip_address()` which parses (or rejects) the input. Because later on, your requirements may change; suddenly your app must accept *hostnames*, *IPv6* addresses, CIDR netmasks or who knows what else. Big problem with 4 edits; no big problem with 1 edit, just adapt the validator function.
