### ISSUE TITLE
ListBox _keypress_max_left/right incorrectly indicate unhandled input

### ISSUE THREAD

**Issue by thesquelched** [urwid/urwid#305]
##### Description:
`ListBox._keypress_max_left` and `ListBox._keypress_max_right` handle the input (by moving to the top or bottom of the `ListBox`, respectively), but they return `True`, which causes the `ListBox` to treat those keys as though they were not handled.

##### Affected versions (if applicable)
- [x] `master` branch @  16469df
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
1. Have `MainLoop.unhandled_input` raise an exception if the key is `home` or `end`
2. Make a `ListBox` with a `SimpleFocusListWalker` and at least one widget
3. Run app and press either `home` or `end`

##### Expected/actual outcome
Expected: nothing happens
Actual: exception is raised

**Comment by bminusl** [comment]
I also encountered this bug while working on a TUI --- 20 minutes of debugging to understand the source. The fix is dead simple: delete `return True`.

- https://github.com/urwid/urwid/blob/c93aeb23fbca0ce8f12187ebc3ca330443a3bf6b/urwid/listbox.py#L1001
- https://github.com/urwid/urwid/blob/c93aeb23fbca0ce8f12187ebc3ca330443a3bf6b/urwid/listbox.py#L1006

Until this is fixed upstream, monkeypatching can be used as a temporary fix.
