### ISSUE TITLE
urwid not working on git bash on windows

### ISSUE THREAD

**Issue by Malex** [urwid/urwid#314]
##### Description:
[I've been using urwid on a small application, both under Linux and under windows. Of course under windows it doesn't work, but I have a workaround of just printing some of the info directly on the terminal. Afaik, urwid works on cygwin, so I was wandering whether is it possible to port it under git bash as well (git bash is a bash shell you can install together with git) and works similarly to cygwin. But under that shell I get the NameError you get on regular windows. Is it possible to make it work and/or whether there's any plan for future support]

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
[...]

##### Expected/actual outcome
[...]

**Comment by averydark** [comment]
AFAIK, you would need to create an extension for `unicurses` which does work on Windows. The shell's used by each of these applications run their own sandboxed version of bash which depends on the Windows API.

Creating a ported fork to `unicurses` would fix this issue and you wouldn't need to rely on any of the subsequent shells because the Windows API would understand those calls. 

I do know that the shell calls are mostly dependent on the underlying system which is why it depends on the shell. Cygwin is a speical case in which the shell is ported to windows which is why some (or most) things work as expected.

This library depends on the curses library which unix specific.

**Comment by penguinolog** [comment]
Since release 2.4.1 urwid support Windows natively + WSL
