### ISSUE TITLE
Palette Test fails in 24-bit mode

### ISSUE THREAD

**Issue by richrd** [urwid/urwid#371]
##### Description:
Running examples/palette_test.py and switching to 24-bit mode crashes with `KeyError: 16777216
`. I tested on Konsole, gnome-terminal and guake.

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [X] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
Run the palette_test.py example and try 24-bit color.

##### Expected/actual outcome
Display 24-bit colors, or at least don't crash.

**Comment by tonycpsu** [comment]
You've indicated that you're using the latest stable branch from PyPi, but that version does not include 24-bit color support.  If you're running the example from github but the version of urwid that's being used is from PyPi, this would be expected behavior, and you'd have to upgrade your urwid to the git master version or wait until we release it to PyPi.

**Comment by richrd** [comment]
Thanks! I didn't realize the 24-bit palette feature hasn't been released yet. I installed urwid from sources ans it works fine. Any info of a possible PyPi release date?
