### ISSUE TITLE
256-Color palettes are broken on terminal emulators without 24-bit true color support

### ISSUE THREAD

**Issue by itaisod** [urwid/urwid#404]
##### Description:
Once upgraded to urwid v2.1.0, color palettes which used to render fine as 256-colors are now broken on terminal emulators which don't support 24-bit true colors. Apparently color palettes now default to render as true-color, instead of 256-colors like how it used to be.

Correct (mintty):
![image](https://user-images.githubusercontent.com/10780214/79281185-e9380180-7eba-11ea-8db3-61b90dd1933f.png)

Corrupt (mintty + GNU Screen, also same behavior on macOS's native Terminal.app):
![image](https://user-images.githubusercontent.com/10780214/79281211-f48b2d00-7eba-11ea-8504-c582c4d3df69.png)

By doing git bisect I've concluded it was introduced by commit f6f5586. Originally encountered on this issue: https://github.com/mitmproxy/mitmproxy/issues/3936

##### Affected versions (if applicable)
- [x] `master` branch (commit 9c70860)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
1. Open a terminal emulator with 256-colors support but without 24-bit color support (e.g. macOS's Terminal.app, or GNU Screen v4.06.02 over any terminal - you can simply run `screen examples/palette_test.py`).
2. Execute `examples/palette_test.py` and choose "256-Colors".

##### Expected/actual outcome
The title "Urwid Palette Test" should be visible. In reality it's invisible because it has a black background.

**Comment by tonycpsu** [comment]
b747f28 (branch `fix_404_high_color`) fixes this issue in `palette_test` for me on Terminal.app.  Will await confirmation from reporter before merging.

**Comment by itaisod** [comment]
Can confirm, seems to work correctly now. Tested both on Terminal.app and GNU screen. Thank you!
<img width="762" alt="image" src="https://user-images.githubusercontent.com/10780214/79378370-dfb7a380-7f65-11ea-916e-66ddfd621782.png">

**Comment by tonycpsu** [comment]
👍

**Comment by clevcode** [comment]
I think I have a related issue.

Using the latest urwid version installed directly from the github repo, and running the tests within gnome-terminal with TERM=xterm-256color.

When running palette_test.py directly, it works fine. When running palette_test.py from within an urwid.Terminal widget, the "16-Colors" option is shown correctly, but the rest are broken. I get monochrome blinking text instead of colors. I noted that TERM was set to "linux" within the urwid.Terminal widget, and tested setting it to xterm-256color instead, but it didn't make any difference.
